### ISSUE TITLE
Theme is overriding user font

### ISSUE THREAD

**Issue by chrisgriffin** [emilyemorehouse/spacegray-eighties-ui#12]
I switched to this theme and noticed my default font changed even though it still remained the same in my settings. I did some debugging and traced it back to this theme.

I am using Atom 0.124.0

**Comment by mikebranski** [comment]
From the [theming docs](https://atom.io/docs/latest/creating-a-theme#creating-a-syntax-theme):

> Note: It's advised to not specify a `font-family` in your syntax theme because it will override the Font Family field in Atom's settings. If you still like to recommend a font that goes well with your theme, we recommend you do so in your README.

[Spacegray Dark UI](https://atom.io/packages/spacegray-dark-ui) seems to specify their font stack in a way that doesn't override the user's `fontFamily` setting.
