### ISSUE TITLE
Improve appearance of scrollbar

### ISSUE THREAD

**Issue by denysbutenko** [emilyemorehouse/spacegray-eighties-ui#13]
Need to improve appearance of scrollbar.

I use minimap package on screenshot.

![screenshot 2015-01-20 20 51 20](https://cloud.githubusercontent.com/assets/351613/5823556/64ccb06a-a0e6-11e4-97ed-72bebd07adb1.png)

**Comment by jovanmaric** [comment]
Update 1.1.0 should have fixed it, however the edit does not reflect on the editor scrollbars :(

**Comment by emilyemorehouse** [comment]
Can you post a screenshot? I'm on a Mac so the scrollbars are different. Works for me.

**Comment by jovanmaric** [comment]
![image](https://cloud.githubusercontent.com/assets/3003740/11771041/5214acda-a20b-11e5-9a95-849989b791e4.png)

Here is a screenshot. The folder tree does look great, now only the editor :). I'm running OSX Yosemite (10.10.5) if that means anything.

**Comment by emilyemorehouse** [comment]
Ah I see, it's fixed now! Atom does some weird things depending on your 'show scroll bars' setting so it looked way different for me. 
Thanks for the catch!
