### ISSUE TITLE
Deprecation issues

### ISSUE THREAD

**Issue by kaslusimoes** [emilyemorehouse/spacegray-eighties-ui#25]
INFO: ArchLinux using AUR package 'atom-editor 0.188.0-1'

Atom complains me about these 3 deprecated selectors
In index.less: Use the `atom-pane` tag instead of the `pane` class.
In index.less: Use the `atom-text-editor` tag instead of the `editor` class.
In index.less: Use the `atom-pane-container` tag instead of the `panes` class.

**Comment by TimohStudios** [comment]
Still all three present
