### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by johnmichel** [emilyemorehouse/spacegray-eighties-ui#26]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `spacegray-eighties-ui` package
```
ThemePackage.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:460:9)
ThemePackage.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:471:32)
ThemePackage.loadStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:453:38)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:47:19)
ThemePackage.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:43:12)
```

Atom v0.200.0 on OS X 10.10.3

The API call in use will be [deprecated on June 1](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html).

**Comment by johnmichel** [comment]
@emilyemorehouse Would a PR with this fix be a better route?

**Comment by emilyemorehouse** [comment]
A PR would be great. I don't actually use Atom so keeping up packages gets
tough. Thanks!

**Comment by johnmichel** [comment]
@emilyemorehouse #27 should cover the necessary changes.

If you'd like to transfer the repo to to me for future maintenance, that's fine as well.
