### ISSUE TITLE
Syntax theme

### ISSUE THREAD

**Issue by denysdovhan** [emilyemorehouse/spacegray-eighties-ui#30]
What the syntax theme is used on this screenshot? Can anybody help me to find it out?

[twilight-syntax-spacegray-eighties](https://atom.io/packages/twilight-syntax-spacegray-eighties) looks different, than this.

![image](https://cloud.githubusercontent.com/assets/3459374/15859551/440afcb8-2cce-11e6-829b-c0753673c170.png)

**Comment by ostrgard** [comment]
@denysdovhan : it's this one: https://atom.io/themes/base16-eighties-dark-syntax

In case you didn't find it in the meantime, and are still looking ;)

**Comment by denysdovhan** [comment]
@ostrgard thank you!
